# Generated by Django 4.2.9 on 2024-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=250)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
