# Generated by Django 4.2.9 on 2024-08-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='photo',
        ),
    ]
